### ISSUE TITLE
Custom cursor extension shows as brown

### ISSUE THREAD

**Issue by phYnc12** [flathub/net.runelite.RuneLite#18] opened 2022-06-29 22:21 UTC
When using the pre-installed extension Custom Cursor any apart from RS gold/silver display as flat brown colour. Tested on ubuntu and manjaro

**Comment by Nightfirecat** [comment] 2022-06-30 06:23
Duplicate of runelite/runelite#8731

**Closed** 2022-06-30 16:16 UTC
